### ISSUE TITLE
RPC request params validation

### ISSUE THREAD

**Issue by shunsukew** [AcalaNetwork/subway#166]
Some RPC methods body params should be validated before reaching backend nodes.
One use-case we can come up with is block range, it would be nice if we could validate and return an error if requested block ranges exceed the configured number allowed.

Possible ideas are
- using the name `validate` middleware for future extendability and rename existing `validate` middleware to `debug`.
- building another middleware called `block_range`

**Comment by xlc** [comment]
can you provide some specific examples? an example config that you would like to be able to use

**Comment by shunsukew** [comment]
The most simple case is configuring in yaml to set block range number for `Filter` type.
I think block range validation should be applicable to `ty: Filter` (which doesn't exist at this moment).
And checking param type and its values inside `block_range` middleware.
```
- method: eth_newFilter
    cache:
      size: 0
    params:
      - name: Filter
        ty: Bytes
        range: 1000
```

Another possible option is using an extension. All validation rules are defined there.
```
pub struct ValidationConfig {
    pub max_block_range: Option<u64>,
    pub max_call_data_size: Option<usize>,
}
```
and set config in yaml like
```
params
- method: eth_getLogs
    cache:
      size: 0
    validate:
        block_range: 1000
    params:
      - name: Filter
        ty: Bytes
```
